CREATE USER NISOFT_GLBG PROFILE DEFAULT IDENTIFIED BY nisoft DEFAULT TABLESPACE NISOFT_DATA_GLBG TEMPORARY TABLESPACE TEMP QUOTA UNLIMITED ON NISOFT_DATA_GLBG ACCOUNT UNLOCK;
GRANT UNLIMITED TABLESPACE TO NISOFT_GLBG WITH ADMIN OPTION;
GRANT CONNECT TO NISOFT_GLBG WITH ADMIN OPTION;
GRANT EXP_FULL_DATABASE TO NISOFT_GLBG WITH ADMIN OPTION;
GRANT IMP_FULL_DATABASE TO NISOFT_GLBG WITH ADMIN OPTION;
GRANT RESOURCE TO NISOFT_GLBG WITH ADMIN OPTION;
