---Update the XXXX as per the required schema  
CREATE SMALLFILE TABLESPACE NISOFT_DATA_XXXX DATAFILE '+DATA' SIZE 300M REUSE AUTOEXTEND ON NEXT 10240K MAXSIZE 2048M LOGGING EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;
