set define off;
INSERT INTO NISOFT_GLBG.operational_areas (OPERATIONAL_AREA_KEY, DESCRIPTION_LANG1) VALUES ('GLBG0000','GLENBROOK BESS COMMON SERVICES');
INSERT INTO NISOFT_GLBG.operational_areas (OPERATIONAL_AREA_KEY, DESCRIPTION_LANG1) VALUES ('GLBG0010','GLENBROOK BESS UNIT 1');
INSERT INTO NISOFT_GLBG.operational_areas (OPERATIONAL_AREA_KEY, DESCRIPTION_LANG1) VALUES ('GLBG0020','GLENBROOK BESS UNIT 2');
INSERT INTO NISOFT_GLBG.operational_areas (OPERATIONAL_AREA_KEY, DESCRIPTION_LANG1) VALUES ('GLBG0030','GLENBROOK BESS UNIT 3');
INSERT INTO NISOFT_GLBG.operational_areas (OPERATIONAL_AREA_KEY, DESCRIPTION_LANG1) VALUES ('GLBG0040','GLENBROOK BESS UNIT 4');